version: '3'
services:
  splitter_api:
    build: ./api
    ports:
      - "8005:8001"
    volumes:
      - ./api/app:/app/app
    env_file:
      - .env.local
    networks:
      - mor_bridge_network

networks:
  mor_bridge_network:
    external: true
