MORCORE_MELDR_ONDERWERPEN = {
    "Grofvuil": {
        "wijken": [
            "Rotterdam Centrum", 
            "Delfshaven", 
            "Noord", 
            "Hillegersberg-Schiebroek", 
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
        ],
    },
    "Zwerfafval": {
        "buurten": {
            "Stadsdriehoek",
        },
    },
    "Afvalbak": {
        "buurten": {
            "Stadsdriehoek",
        },
    },
    "Blad of bloesem": {
        "buurten": {
            "Stadsdriehoek",
        },
    },
    "Uitwerpselen": {
        "buurten": {
            "Stadsdriehoek",
        },
    },
    "Gladheid": {
        "buurten": {
            "Stadsdriehoek",
            "Oude Westen",
            "Cool",
            "Cs Kwartier",
            "Nieuwe Werk",
            "Dijkzigt",
            "Delfshaven",
            "Bospolder",
            "Tussendijken",
            "Spangen",
            "Nieuwe Westen",
            "Middelland",
            "Oud Mathenesse",
            "Witte Dorp",
            "Middelland",
            "Schiemond",
            "Kleinpolder",
            "Noord Kethel",
            "Schieveen",
            "Zestienhoven",
            "Overschie",
            "Landzicht",
            "Agniesebuurt",
            "Provenierswijk",
            "Bergpolder",
            "Blijdorp",
            "Liskwartier",
            "Oude Noorden",
            "Blijdorpsepolder",
            "Schiebroek",
            "Hillegersberg Zuid",
            "Hillegersberg Noord",
            "Terbregge",
            "Molenlaankwartier",
            "Rubroek",
            "Nieuw Crooswijk",
            "Oud Crooswijk",
            "Kralingen West",
            "Kralingen Oost",
            "Kralingse Bos",
            "De Esch",
            "Struisenburg",
        },
    },
}