MORCORE_MELDR_ONDERWERPEN = {
    # inzameling
    "Grofvuil": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    # wrt & inzameling
    "Afval naast wijkcontainer": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    # wrt
    "Zwerfafval": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    # wrt
    "Afvalbak": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    # wrt
    "Onkruid": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    # wrt
    "Blad of bloesem": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    # wrt
    "Uitwerpselen": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    # wrt
    "Gladheid": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    "Graffiti": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    "Vervuiling in het water": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    "Huiscontainer": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    "Wijkcontainer": {
        "wijken": [
            # noord
            "Rotterdam Centrum",
            "Delfshaven",
            "Nieuw Mathenesse",
            "Noord",
            "Hillegersberg-Schiebroek",
            "Overschie",
            "Kralingen-Crooswijk",
            "Prins Alexander",
            "Spaanse Polder",
            "Rotterdam-Noord-West",
            "Rivium",
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    # plaagdierbestrijding
    "Overlast insecten": {},
    "Overlast ongedierte": {},
    # handhaving
    "Parkeeroverlast aanhangwagen": {
        "wijken": [
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    "Parkeeroverlast voertuig": {
        "wijken": [
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    "Voertuigwrak": {
        "wijken": [
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    "Parkeeroverlast (brom-)fiets": {
        "wijken": [
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    "Parkeeroverlast Deelscooter": {
        "wijken": [
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    "Parkeeroverlast Deel(bak-)fiets": {
        "wijken": [
            # zuid
            "Feijenoord",
            "IJsselmonde",
            "Charlois",
            "Hoogvliet",
            "Pernis",
            "Rozenburg",
            "Hoek van Holland",
            "Botlek-Europoort-Maasvlakte",
            "Vondelingenplaat",
            "Waalhaven-Eemhaven",
        ],
    },
    "Gevaarlijk afval": {},
    "Drugsafval": {},
}

## buurten
# "Oude Westen",
# "Stadsdriehoek",
# "Cool",
# "Cs Kwartier",
# "Nieuwe Werk",
# "Dijkzigt",
# "Delfshaven",
# "Bospolder",
# "Tussendijken",
# "Spangen",
# "Nieuwe Westen",
# "Middelland",
# "Oud Mathenesse",
# "Witte Dorp",
# "Middelland",
# "Schiemond",
# "Kleinpolder",
# "Noord Kethel",
# "Schieveen",
# "Zestienhoven",
# "Overschie",
# "Landzicht",
# "Agniesebuurt",
# "Provenierswijk",
# "Bergpolder",
# "Blijdorp",
# "Liskwartier",
# "Oude Noorden",
# "Blijdorpsepolder",
# "Schiebroek",
# "Hillegersberg Zuid",
# "Hillegersberg Noord",
# "Terbregge",
# "Molenlaankwartier",
# "Rubroek",
# "Nieuw Crooswijk",
# "Oud Crooswijk",
# "Kralingen West",
# "Kralingen Oost",
# "Kralingse Bos",
# "De Esch",
# "Struisenburg",
